/* IrisSNN v1 — neuromorphic archetype (ODIN/Loihi direction): integrate-and-fire spiking
 * neurons, rate-coded inputs, runtime-loaded weights AND thresholds.
 *
 * Computation class differs from the other columns (spikes, not MACs-on-values), so the
 * comparison is at the ACCURACY level (like the DPU row), not bit-exact-to-TFLite. The
 * engine itself is fully integer and deterministic: a per-sample spike-count checksum is
 * its own golden (established in csim, must reproduce exactly on the board).
 *
 * Conversion (done host-side, becomes runtime config):
 *   input rate r_k = max(0, xq+17)/256, generated by a deterministic Bresenham phase acc
 *   per-step hidden current = 256*sum(w1*spike) + b1  (expected value = the MLP's acc1)
 *   theta1[j] = 256/scale1[j] (from m0/shift) -> hidden spike rate mirrors (h_q - zp)/256
 *   same construction for the output layer; class = argmax spike count.
 *   IF neurons: reset-by-subtraction, floor at 0 (the ReLU-equivalent SNN neuron).
 * cfg: [0]=T [1]=n_samp | w1[32] b1[8] th1[8] | w2[24] b2[3] th2[3] at fixed offsets.
 */
#include <stdint.h>

#define SNN_CFG_W 96
#define SNN_XMEM_B 1024
#define SNN_YMEM_B 256
#define CFG_T 0
#define CFG_W1 8
#define CFG_B1 40
#define CFG_TH1 48
#define CFG_W2 56
#define CFG_B2 80
#define CFG_TH2 83

void iris_snn(int reps, int n_samp,
              int32_t cfg[SNN_CFG_W], int8_t xmem[SNN_XMEM_B], int8_t ymem[SNN_YMEM_B],
              uint32_t *cs_out, int *acc_out)
{
#pragma HLS interface s_axilite port=reps    bundle=ctrl
#pragma HLS interface s_axilite port=n_samp  bundle=ctrl
#pragma HLS interface s_axilite port=cfg     bundle=ctrl
#pragma HLS interface s_axilite port=xmem    bundle=ctrl
#pragma HLS interface s_axilite port=ymem    bundle=ctrl
#pragma HLS interface s_axilite port=cs_out  bundle=ctrl
#pragma HLS interface s_axilite port=acc_out bundle=ctrl
#pragma HLS interface s_axilite port=return  bundle=ctrl

    int32_t c_[SNN_CFG_W];
#pragma HLS array_partition variable=c_ complete
    for(int i=0;i<SNN_CFG_W;i++){
#pragma HLS pipeline II=1
        c_[i]=cfg[i]; }
    int T=c_[CFG_T];

    uint32_t cs=0; int good=0;
REPS:
    for(int r=0;r<reps;r++){
#pragma HLS loop_tripcount min=1 max=100000
        cs=0x811c9dc5u; good=0;
SAMPLES:
        for(int s=0;s<n_samp;s++){
#pragma HLS loop_tripcount min=150 max=150
            int32_t xi[4], ax[4], V[8], U[3], cnt[3];
#pragma HLS array_partition variable=xi complete
#pragma HLS array_partition variable=ax complete
#pragma HLS array_partition variable=V complete
#pragma HLS array_partition variable=U complete
#pragma HLS array_partition variable=cnt complete
            for(int k=0;k<4;k++){
#pragma HLS unroll
                xi[k]=(int32_t)xmem[4*s+k]+17;   /* signed: inhibitory rail for x < zp */
                ax[k]=128; }
            for(int j=0;j<8;j++){
#pragma HLS unroll
                V[j]=0; }
            for(int o=0;o<3;o++){
#pragma HLS unroll
                U[o]=0; cnt[o]=0; }
TSTEPS:
            for(int t=0;t<T;t++){
#pragma HLS pipeline II=2
#pragma HLS loop_tripcount min=256 max=256
                int32_t sx[4];
#pragma HLS array_partition variable=sx complete
                for(int k=0;k<4;k++){
#pragma HLS unroll
                    int32_t mag=xi[k]<0?-xi[k]:xi[k];
                    ax[k]+=mag;
                    int fire=(ax[k]>=256)?1:0;
                    if(fire) ax[k]-=256;
                    sx[k]=fire?(xi[k]<0?-1:1):0; }
                int32_t hs[8];
#pragma HLS array_partition variable=hs complete
                for(int j=0;j<8;j++){
#pragma HLS unroll
                    int32_t cur=c_[CFG_B1+j];
                    for(int k=0;k<4;k++){
#pragma HLS unroll
                        if(sx[k]) cur+=sx[k]*(c_[CFG_W1+4*j+k]<<8); }
                    int32_t v=V[j]+cur;
                    int32_t th=c_[CFG_TH1+j];
                    hs[j]=(v>=th)?1:0;
                    V[j]=hs[j]?(v-th):v; }
                for(int o=0;o<3;o++){
#pragma HLS unroll
                    int32_t cur=c_[CFG_B2+o];
                    for(int j=0;j<8;j++){
#pragma HLS unroll
                        if(hs[j]) cur+=c_[CFG_W2+8*o+j]<<8; }
                    int32_t u=U[o]+cur;
                    int32_t th=c_[CFG_TH2+o];
                    if(u>=th){ cnt[o]++; u-=th; }
                    U[o]=u; }
            }
            int best=0;
            for(int o=0;o<3;o++){
#pragma HLS unroll
                uint8_t b=(uint8_t)cnt[o];
                cs=(cs^(uint16_t)b)*16777619u;
                if(cnt[o]>cnt[best]) best=o;
            }
            if(best==ymem[s]) good++;
        }
    }
    *cs_out=cs; *acc_out=good;
}
